=== crepka/annotations/BookPageColumnLine.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- definition of simple elements -->
<xs:element name="title" type="xs:string"/>
<xs:element name="author" type="xs:string"/>
<xs:element name="publicationyear" type="xs:string"/>
<xs:element name="heading" type="xs:string"/>
<xs:element name="chapter"/>
<xs:element name="i" type="xs:string"/>

<!-- definition of attributes -->
<xs:attribute name="p1861" type="xs:integer"/>
<xs:attribute name="pagenumber" type="xs:integer"/>
<xs:attribute name="id" type="xs:string"/>
<xs:attribute name="p19c" type="xs:integer"/>
<xs:attribute name="p5c" type="xs:integer"/>
<xs:attribute name="value" type="xs:string"/>
<xs:attribute name="type" type="xs:string"/>
<xs:attribute name="style" type="xs:string"/>

<!-- definition of complex elements -->
<xs:element name="book">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="title"/>
      <xs:element ref="author"/>
      <xs:element ref="publicationyear"/>
      <xs:element ref="printpage" minOccurs="0" maxOccurs="100"/>
      <xs:element ref="page" minOccurs="0" maxOccurs="100"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="printpage">
	<xs:complexType mixed="true">
		<xs:sequence>
			<xs:element ref="heading" minOccurs="0"/>
			<xs:element ref="page" minOccurs="0" maxOccurs="100"/> <!-- yuck -->
		</xs:sequence>
		<xs:attribute ref="p1861"/>
		<xs:attribute ref="pagenumber"/>
		<xs:attribute ref="id"/>
		<xs:attribute ref="p19c"/>
		<xs:attribute ref="p5c"/>
	</xs:complexType>
</xs:element>

<xs:element name="page">
	<xs:complexType mixed="true">
		<xs:sequence>
			<xs:element ref="column" minOccurs="0" maxOccurs="100"/><!-- yuck -->
		</xs:sequence>
		<xs:attribute ref="p1861"/>
		<xs:attribute ref="id"/>
		<xs:attribute ref="p19c"/>
		<xs:attribute ref="p5c"/>
	</xs:complexType>
</xs:element>

<xs:element name="column" >
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="chapter" minOccurs="0"/>
			<xs:element ref="line" maxOccurs="100"/><!-- this can't be right -->
		</xs:sequence>
		<xs:attribute ref="value"/>
	</xs:complexType>
</xs:element>

<xs:element name="line">
	<xs:complexType mixed="true">
		<xs:sequence>
			<xs:element ref="i"  minOccurs="0"/>
		</xs:sequence>
		<xs:attribute ref="style"/>
	</xs:complexType>
</xs:element>

</xs:schema>

=== crepka/annotations/UCLARouse32-Transcription.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="BookPageColumnLine.xsl"?>
<book 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="BookPageColumnLine.xsd">
	<title>Transcription of Book of Hours</title>
	<author>UCLA Rouse MS 32</author>
	<publicationyear>c1400</publicationyear>
		<page p19c="25">
			<column value="v">
				<line>cum in uigore spiritus in[hala]turus.</line>
				<line>Ave spiritus sancti [Dolo]ris gladium</line>
				<line>sponsa Maria gratia plena domin'</line>
				<line>tecum benedicta tu in mulieribus et bene</line>
				<line>dictus fructus uentis tui Iesus. Dom</line>
				<line>ina sancta Maria uirgo glo[rio]sissima </line>
				<line>mater dei et hominis adora[ns] te ammo (admo)</line>
				<line>neo et deprecor per illum doloris gladium </line>
				<line>qui tuam felicissimus [animam per]tran</line>
				<line>sivit dum sentires in spiritu hora matu</line>
				<line>tina filium tuum de[tineri] cola[phis] spu</line>
				<line>tis vinculis[que gravari et iudicibus pra]esen</line>
				<line>[t]ari fac me mis[erum peccatorem] partici</line>
				<line>pem eiusdem doloris [et da ut] in satisfa</line>
				<line>ctione perseverans laqueos capturas et </line>
				<line>vincula diaboli mundi [pro]priaeque fragili</line>
				<line>tatis euadam tu(a)e gubernationis mode</line>
				<line>ramine fruiturus. </line>
				<line>Ave celestis Regis mater maria gra</line>
				<line>tia plena dominus tecum benedic</line>
				<line>ta tu in mulieribus et benedictus fructus</line> 
				<line>uentris tui Iesus. Domina sancta M</line>
			</column>
		</page>
		<page p19c="55" id="55r">
			<column value="r">
				<line>salutem omnium tam vivorum quam mor</line>
				<line>tuorum. Rogo te domine per ipsum sacro</line>
				<line>sanctum et vivificum misterium corporis et</line>
				<line>sanguinis tui quo cotidie in ecclesia tua </line>
				<line>pascimur et potamur abluimur et sancti</line>
				<line>ficamur. atque unius summe diuinitatis </line>
				<line>participes efficimur da michi uirtutes tu</line>
				<line>as sanctas quibus repletus bona conscienci</line>
				<line>a ad alatare tuum accedam. Ita ut hec cele</line>
				<line>stia sacramenta efficiantur michi salus</line>
				<line>et uita. Tu enim dixisti ore tuo sancto et </line>
				<line>benedicto. Panis quem ego dabo caro me </line>
				<line>a est pro mundi uita. Qui manducat me </line> 
				<line>viva vivet propter me et ipse manet in me </line>
				<line>et ego in eo Ego sum panis vivus qui de coe</line>
				<line>lo descendi. Si quis manducaverit ex hoc </line>
				<line>pane uiuet in eternum. Panis dulcissi</line>
				<line>me. sana palatum cordis mei. ut sentiam </line>
				<line>s{u}auitatem amoris tui. Sana eum ab o</line>
				<line>mni languore. ut nullam preter te senti</line>
				<line>at dulcedinem, nullum preter te querat </line>
				<line>amorem. nullam preter te amet pulch</line>
			</column>
		</page>
</book>

=== crepka/annotations/OnLuke-Transcription.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="BookPageColumnLine.xsl"?>
<book 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="BookPageColumnLine.xsd">
	<title>Corpus Christianorum Series Latina 87, Scripta Arriana Latina</title>
	<author>Roger Gryson</author>
	<publicationyear>1982</publicationyear>
	<printpage pagenumber="199" id="Edition199"> 
		<heading>Under Construction</heading>
		<page p19c="20" p5c="5" id="19c020">
			<column value="main">
				<line>This page is under construction.</line>
				<line>It will represent the Commentary on Luke in TEI XML, starting with Gryson 1982 and adjusting with new readings.</line>
				<line>Volunteer work on this task would be appreciated.</line>
			</column>
		</page>
	</printpage>
</book>

=== crepka/annotations/UCLARouse32-Translation.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="BookPageColumnLine.xsl"?>
<book 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="BookPageColumnLine.xsd">
	<title>Translation of Book of Hours</title>
	<author>UCLA Rouse MS 32</author>
	<publicationyear>c1400</publicationyear>
		<page p19c="25" id="25v">
			<column value="v">
				<line>about to exhale in the power of the spirit.</line>
				<line>Hail holy spirit, sword of sorrow,</line>
				<line>maiden Mary, full of grace, the Lord is</line>
				<line>with you. Blessed are you among women and blessed</line>
				<line>is the fruit of your womb Jesus. Holy </line>
				<line>lord Mary, most glorious virgin, </line>
				<line>mother of God and man, giving priase, I urge </line>
				<line>and beg you through the sorrowful sword </line>
				<line>which your most blessed spirit passed through</line> 
				<line>sensing in spirit the morning hour </line>
				<line>your son was arrested, beaten, spat upon,</line>
				<line>and bound in the presence of officials and judges.</line> 
				<line>Let me, a miserable sinner, share </line>
				<line>in the same suffering and also enjoy the lasting</line> 
				<line>satisfaction of ensnaring, capturing, and </line>
				<line>binding the world of the devil and his own,</line> 
				<line>by your very fragility, governance,</line> 
				<line>and demeanor.</line>
				<line>Hail mother of the heavenly King, Mary full</line>
				<line>of grace, the Lord is with you. Blessed </line>
				<line>are you among women and blessed is the fruit</line>
				<line>of your womb Jesus. Holy lord M</line>
			</column>
		</page>
		<page p19c="55" id="55r">
			<column value="r">
				<line>the salvation of all both living and dead.</line>
				<line>I entreat you Lord through the same sacred</line>
				<line>and life-giving mystery of your body and</line>
				<line>blood by which daily in your church</line>
				<line>we are fed and and given drink, we are washed and sanctified,</line>
				<line>and so in one most high divinity </line>
				<line>we are caused to partake, give me your holy virtues </line>
				<line>by which a good conscience having been refilled </line>
				<line>I might draw near to your altar, so that these heavenly</line>
				<line>sacraments will effect in me salvation</line>
				<line>and life. With your own sacred and blessed mouth you have said:</line>
				<line>The bread which I give is my flesh </line>
				<line>for the life the of the world. One who eats me</line>
				<line>will live because of me and that one remains in me</line>
				<line>and I in him. I am the living bread which descended from heaven.</line>
				<line>Whoever eats of this </line>
				<line>bread will live forever. Sweetest bread,</line>
				<line>heal the palate of my heart so that I might feel</line>
				<line>the sweetness of your love. Heal it from every</line>
				<line>sickness so that it might feel no sweetness except you, </line>
				<line>seek no love except you, love no beau[ty] except you</line>
			</column>
		</page>
</book>
